environment: dev

dev:
  logging:
    level: DEBUG
    rotation:
      max_bytes: 1048576
      backup_count: 2

prod:
  logging:
    level: WARNING
    rotation:
      max_bytes: 10485760
      backup_count: 5

logging:
  folder: logs        # relative to this module
  file_name: app.json

app_name: my_app